### PR TITLE
Switches to bookdown-appendix approach

### LINKED ISSUE #303: Cannot knit manuscript if appendix.rmd is not located in main directory
**Describe the bug**
When knitting a manuscript with an appendix.rmd (specified via yaml header) that is not located in the same directory as the main document, an error is thrown:
```
Quitting from lines 2-3 (main.rmd) 
Quitting from lines NA-4 (main.rmd) 
Fehler in gzfile(file, "rb") : kann Verbindung nicht öffnen
Ruft auf: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> readRDS -> gzfile
Ausführung angehalten
```

**To Reproduce**
I prepared a minimal reproducible example here: https://drive.google.com/open?id=15XDCE6_SUqFekj-q85_ruGbOB10UaLSd

### LINKED ISSUE #496: Bug in appendix: ampersand appearing instead of 'and'
Hello,

Thank you for such a great package.

I would like to report a bug regarding the appearance, in appendices only, of an ampersand in non-parenthetical citations for references with two authors, where 'and' should appear instead. The error appears in both the apa6 and the apa7 document classes.

It seems as though the filter that distinguishes parenthetical and non-parenthetical citations only works in the main document.

**To reproduce**

1. Create a main document that includes an appendix;
2. Write a *non-parenthetical* citation for a reference with two authors in the main document, as well as in the appendix;
3. Knit the main document (the appendix will be automatically knitted);
4. Notice in the output that the main document has 'and' linking the two authors (correct APA), whereas the appendix has '&'.

Thank you very much for your attention

### PR DESCRIPTION
**Pull request by crsh**
This PR removes my hacky solution to automagically add appendices to the end of the document in favor of the much more elegant bookdown feature (as documented [here](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers)).

As a consequence it makes the following additional changes:

- `render_appendix()` is now defunct because it is no long needed
- `base64enc` import is removed because it is no longer needed
- Skeletons now use fenced div syntax for bibliography placement

I think this fixes #496 #484 #249 and generally resolves issues like #322 #353

Finally, I imagine this potentially fixes #303. Could you give it a try, @mariusbarth?

This change additionally needs to be documented in the manual.

### CODE REVIEW

**Comment by mariusbarth** [comment]
On Ubuntu, this works for
  - word documents
  - pdf documents with class options `man` or `doc`
  
Fails for class option `jou`, works if and only if I write `# (APPENDIX) Appendices {-}`, bot not if I omit the `{-}

**Comment by crsh** [comment]
> Also, for all output formats, works if and only if I write # (APPENDIX) Appendices {-}, but not if I omit the `{-}`

Yes, I think that's expected behavior, but may be worth highlighting in the manual.

**Comment by crsh** [comment]
> Fails for class option `jou`, here is the error message:
> 
> ```
> ! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pd
> fstartlink.
> \AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
>                                                   \fi \fi 
> l.655 \end{document}
> ```

Would you be able to provide a minimal reproducible example? The following works for me:

~~~
---
title             : "The title"
classoption       : "jou"

output            : papaja::apa6_pdf
---


# Heading 1
## Subheading 1

# (APPENDIX) Appendix {-} 

# Heading 2
## Subheading 2
~~~

**Comment by crsh** [comment]
@mariusbarth, any idea why the tests are failing? I don't think this is related to a change in our code? Could it be related to a recent update in `tinylabels`?

**Comment by mariusbarth** [comment]
Yes, it is due to some improvements in tinylabels. The tests fail because they depended on unintended side effects. Will fix'em today

**Comment by crsh** [comment]
The LaTeX error seems to be an edge case related to URLs (e.g. in the reference section) breaking across pages. I don't think this is necessarily related to the appendix. Let's make this into a separate issue.

**Pull request merged**
