### PR TITLE
apa R package

### PR DESCRIPTION
**Pull request by lavakumar994**
I would like to download this

### CODE REVIEW

**Comment by crsh** [comment]
@mariusbarth What's the state of this branch?

**Comment by mariusbarth** [comment]
Work on this branch is far from finished, which is why I don't really understand the purpose of this PR.

**Comment by crsh** [comment]
@lavakumar994 could you elaborate?

**Comment by lavakumar994** [comment]
Hi ,

I no longer need the package.

Thanks,
Lava.

**Comment by crsh** [comment]
Thanks for the reply. I'll close this PR then.

**Pull request closed without merging**
