### PR TITLE
Hot fix: Safer detection of Chi^2 test in stat_glue(). #154

### PR DESCRIPTION
**Pull request by crsh**
The problem in #154 seems to be that `stat_glue()` tries to determine, whether there is sample size information in an fundamentally unsafe way. This is a hot fix for the issue, but requires a lot more thought.

### CODE REVIEW

**Review by mariusbarth — APPROVED** [review]
Maybe use `if(identical(variable_label(x$statistic), "$\\chi^2$"))` or `if(any(grepl(variable_label(x$statistic), pattern = "chi^2", fixed = TRUE)))`

**Comment by mariusbarth** [comment]
To further improve stability, I think we could switch to an additional attribute for the `statistic` column (e.g., `attr(x$statistic, "n")`. In the future, we could then drop this attribute if a proper measure of effect size is calculated.

**Comment by crsh** [comment]
Not sure I follow your last comment. Unless I misremember, `n` is used really only when a contigency table test ist reported (as per APA). So I don't think we can drop it with any other effect size measures?

**Comment by crsh** [comment]
I'll merge this PR and open a new issue to improve the handling of `n`.

**Pull request merged**
