### PR TITLE
suggestion to make the text about indentation more understandable

### PR DESCRIPTION
**Pull request by alexholcombe**
and to also note the (surprising to me) thing that two empty lines are needed to create a new paragraph in the output document

### CODE REVIEW

**Comment by crsh** [comment]
Hi Alex,

thank you for the pull request. I had never noticed that it takes two empty lines to create a new paragraph. Interestingly, this somehow has to do with the `>` that introduces the multiline contents of the `author_note` variable:

~~~
author_note: >
  Complete departmental affiliations for each author (note the indentation, if you start a new paragraph).
~~~

If you replace it with a `|` a new paragraph is created with only one empty line:

~~~
author_note: |
  Complete departmental affiliations for each author (note the indentation, if you start a new paragraph).
~~~

Would you be willing to amend your pull request accordingly for both `author_note` and `abstract`?

Best regards,
Frederik

**Comment by alexholcombe** [comment]
Aha. I've amended accordingly (assuming I understood everything you wrote).

**Comment by crsh** [comment]
Thanks. I think I will simplify this a little by making `|` the default.

**Comment by alexholcombe** [comment]
That sounds very sensible. I  have no sense of the relative roles of the “>” versus “|”, why both exist.

**Pull request merged**
